# http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --region ${AWS_REGION})
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t saic-prod-jenkins .
      - docker tag saic-prod-jenkins:latest 237844026185.dkr.ecr.us-east-1.amazonaws.com/saic-prod-jenkins:latest
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push 237844026185.dkr.ecr.us-east-1.amazonaws.com/saic-prod-jenkins:latest
      - envsubst < "Dockerrun.aws.json.template" > "Dockerrun.aws.json"
artifacts:
  files:
    - 'Dockerrun.aws.json'
    - '.ebextensions/**/*'
